/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.wise.comp.pivotmatrix.schema.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroSummaryCellRow extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5674964035220039620L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroSummaryCellRow\",\"namespace\":\"com.wise.comp.pivotmatrix.schema.avro\",\"fields\":[{\"name\":\"row\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroSummaryCell\",\"fields\":[{\"name\":\"summaryValues\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroSummaryValue\",\"fields\":[{\"name\":\"fieldName\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"summaryType\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"count\",\"type\":\"long\"},{\"name\":\"sum\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"value\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"distinctValues\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"textValue\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroSummaryCellRow> ENCODER =
      new BinaryMessageEncoder<AvroSummaryCellRow>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroSummaryCellRow> DECODER =
      new BinaryMessageDecoder<AvroSummaryCellRow>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroSummaryCellRow> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroSummaryCellRow> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroSummaryCellRow>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroSummaryCellRow to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroSummaryCellRow from a ByteBuffer. */
  public static AvroSummaryCellRow fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell> row;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroSummaryCellRow() {}

  /**
   * All-args constructor.
   * @param row The new value for row
   */
  public AvroSummaryCellRow(java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell> row) {
    this.row = row;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return row;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: row = (java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'row' field.
   * @return The value of the 'row' field.
   */
  public java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell> getRow() {
    return row;
  }

  /**
   * Sets the value of the 'row' field.
   * @param value the value to set.
   */
  public void setRow(java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell> value) {
    this.row = value;
  }

  /**
   * Creates a new AvroSummaryCellRow RecordBuilder.
   * @return A new AvroSummaryCellRow RecordBuilder
   */
  public static com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow.Builder newBuilder() {
    return new com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow.Builder();
  }

  /**
   * Creates a new AvroSummaryCellRow RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroSummaryCellRow RecordBuilder
   */
  public static com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow.Builder newBuilder(com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow.Builder other) {
    return new com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow.Builder(other);
  }

  /**
   * Creates a new AvroSummaryCellRow RecordBuilder by copying an existing AvroSummaryCellRow instance.
   * @param other The existing instance to copy.
   * @return A new AvroSummaryCellRow RecordBuilder
   */
  public static com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow.Builder newBuilder(com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow other) {
    return new com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow.Builder(other);
  }

  /**
   * RecordBuilder for AvroSummaryCellRow instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroSummaryCellRow>
    implements org.apache.avro.data.RecordBuilder<AvroSummaryCellRow> {

    private java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell> row;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.row)) {
        this.row = data().deepCopy(fields()[0].schema(), other.row);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroSummaryCellRow instance
     * @param other The existing instance to copy.
     */
    private Builder(com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.row)) {
        this.row = data().deepCopy(fields()[0].schema(), other.row);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'row' field.
      * @return The value.
      */
    public java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell> getRow() {
      return row;
    }

    /**
      * Sets the value of the 'row' field.
      * @param value The value of 'row'.
      * @return This builder.
      */
    public com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow.Builder setRow(java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell> value) {
      validate(fields()[0], value);
      this.row = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'row' field has been set.
      * @return True if the 'row' field has been set, false otherwise.
      */
    public boolean hasRow() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'row' field.
      * @return This builder.
      */
    public com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCellRow.Builder clearRow() {
      row = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroSummaryCellRow build() {
      try {
        AvroSummaryCellRow record = new AvroSummaryCellRow();
        record.row = fieldSetFlags()[0] ? this.row : (java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroSummaryCellRow>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroSummaryCellRow>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroSummaryCellRow>
    READER$ = (org.apache.avro.io.DatumReader<AvroSummaryCellRow>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
