//Globalize.addCultureInfo("ko", {messages: {
//	"dxPivotGrid-grandTotal": "전체 합계",
//    "dxPivotGrid-total": "전체 {0}",
//    "dxPivotGrid-fieldChooserTitle": "필드선택",
//    "dxPivotGrid-showFieldChooser": "필드선택 보기",
//    "dxPivotGrid-expandAll": "전체확장",
//    "dxPivotGrid-collapseAll": "전체축소",
//    "dxPivotGrid-sortColumnBySummary": "\"{0}\"필드로 정렬",
//    "dxPivotGrid-sortRowBySummary": "\"{0}\"로우로 정렬",
//    "dxPivotGrid-removeAllSorting": "전체 정렬제거",
//    "dxPivotGrid-rowFields": "로우필드",
//    "dxPivotGrid-columnFields": "컬럼필드",
//    "dxPivotGrid-dataFields": "데이타필드",
//    "dxPivotGrid-filterFields": "필터필드",
//    "dxPivotGrid-allFields": "전체필드",
//    "dxList-selectAll" : "(모두)"
//}});


Globalize.loadMessages({
	ko: {
	    "Back": "뒤로",
	    "Cancel": "취소",
	    "Clear": "Clear",
	    "Done": "완료",
	    "Loading": "로딩중...",
	    "No": "아니오",
	    "OK": "확인",
	    "Search": "검색",
	    "Select": "선택...",
	    "Yes": "예",
	    "format-currency" : "&#8361",
	    "dxCalendar-ariaWidgetName": "달력",
	    "dxCalendar-todayButtonText": "오늘",
	    "dxCollectionWidget - noDataText": "조회된 데이터가 없습니다",
	    "dxColorView-ariaAlpha": "Transparency",
	    "dxColorView-ariaBlue": "파랑",
	    "dxColorView-ariaGreen": "초록",
	    "dxColorView-ariaHex": "색상코드",
	    "dxColorView-ariaRed": "빨강",
	    "dxDataGrid-applyFilterText": "필터적용",
	    "dxDataGrid-ariaCollapse": "접기",
	    "dxDataGrid-ariaColumn": "컬럼",
	    "dxDataGrid-ariaDataGrid": "데이터그리드",
	    "dxDataGrid-ariaExpand": "확장",
	    "dxDataGrid-ariaFilterCell": "필터 셀",
	    "dxDataGrid-ariaSearchInGrid": "데이터 그리드에서 검색",
	    "dxDataGrid-ariaSelectAll": "모두선택",
	    "dxDataGrid-ariaSelectRow": "로우선택",
	    "dxDataGrid-ariaValue": "값",
	    "dxDataGrid-columnChooserEmptyText": "Drag a column here to hide it",
	    "dxDataGrid-columnChooserTitle": "컬럼선택기",
	    "dxDataGrid-columnFixingFix": "Fix",
	    "dxDataGrid-columnFixingLeftPosition": "왼쪽으로",
	    "dxDataGrid-columnFixingRightPosition": "오른쪽으로",
	    "dxDataGrid-columnFixingUnfix": "Unfix",
	    "dxDataGrid-editingAddRow": "로우추가",
	    "dxDataGrid-editingCancelAllChanges": "변경취소",
	    "dxDataGrid-editingCancelRowChanges": "취소",
	    /* DOGFOOT ktkang 연결보고서 문구 수정  20200525 */
	    "dxDataGrid-editingConfirmDeleteMessage": "항목을 삭제하시겠습니까?",
	    "dxDataGrid-editingDeleteRow": "삭제",
	    "dxDataGrid-editingEditRow": "수정",
	    "dxDataGrid-editingSaveAllChanges": "번경저장",
	    "dxDataGrid-editingSaveRowChanges": "저장",
	    /* DOGFOOT ktkang 한글로 변경  20200123 */
	    "dxDataGrid-editingUndeleteRow": "삭제 취소",
	    "dxDataGrid-excelFormat": "엑셀파일",
	    "dxDataGrid-exportAll": "전체데이터 다운로드",
	    "dxDataGrid-exportSelectedRows": "선택데이터 다운로드",
	    "dxDataGrid-exportTo": "다운로드",
	    "dxDataGrid-exportToExcel": "엑셀다운로드",
	    "dxDataGrid-falseText": "false",
	    "dxDataGrid-filterRowOperationBetween": "Between",
	    "dxDataGrid-filterRowOperationBetweenEndText": "End",
	    "dxDataGrid-filterRowOperationBetweenStartText": "Start",
	    "dxDataGrid-filterRowOperationContains": "Contains",
	    "dxDataGrid-filterRowOperationEndsWith": "Ends with",
	    "dxDataGrid-filterRowOperationEquals": "Equals",
	    "dxDataGrid-filterRowOperationGreater": "Greater than",
	    "dxDataGrid-filterRowOperationGreaterOrEquals": "Greater than or equal to",
	    "dxDataGrid-filterRowOperationLess": "Less than",
	    "dxDataGrid-filterRowOperationLessOrEquals": "Less than or equal to",
	    "dxDataGrid-filterRowOperationNotContains": "Does not contain",
	    "dxDataGrid-filterRowOperationNotEquals": "Does not equal",
	    "dxDataGrid-filterRowOperationStartsWith": "Starts with",
	    "dxDataGrid-filterRowResetOperationText": "Reset",
	    "dxDataGrid-filterRowShowAllText": "전체",
	    "dxDataGrid-groupContinuedMessage": "Continued from the previous page",
	    "dxDataGrid-groupContinuesMessage": "Continues on the next page",
	    "dxDataGrid-groupHeaderText": "Group by This Column",
	    "dxDataGrid-groupPanelEmptyText": "Drag a column header here to group by that column",
	    "dxDataGrid-headerFilterCancel": "Cancel",
	    "dxDataGrid-headerFilterEmptyValue": "(Blanks)",
	    "dxDataGrid-headerFilterOK": "OK",
	    "dxDataGrid-noDataText": "조회된 데이터가 없습니다",
	    "dxDataGrid-searchPanelPlaceholder": "검색...",
	    "dxDataGrid-selectedRows": "선택된 로우",
	    "dxDataGrid-sortingAscendingText": "오름차순 정렬",
	    "dxDataGrid-sortingClearText": "정렬제거",
	    "dxDataGrid-sortingDescendingText": "내림차순 정렬",
	    "dxDataGrid-summaryAvg": "Avg {0}",
	    "dxDataGrid-summaryAvgOtherColumn": "Avg of {1} is {0}",
	    "dxDataGrid-summaryCount": "Count {0}",
	    "dxDataGrid-summaryMax": "Max {0}",
	    "dxDataGrid-summaryMaxOtherColumn": "Max of {1} is {0}",
	    "dxDataGrid-summaryMin": "Min {0}",
	    "dxDataGrid-summaryMinOtherColumn": "Min of {1} is {0}",
	    "dxDataGrid-summarySum": "Sum {0}",
	    "dxDataGrid-summarySumOtherColumn": "Sum of {1} is {0}",
	    "dxDataGrid-trueText": "true",
	    "dxDataGrid-ungroupAllText": "Ungroup All",
	    "dxDataGrid-ungroupHeaderText": "Ungroup",
	    "dxDataGrid-validationCancelChanges": "Cancel changes",
	    "dxDateBox-simulatedDataPickerTitleDate": "Select date",
	    "dxDateBox-simulatedDataPickerTitleDateTime": "Select date and time",
	    "dxDateBox-simulatedDataPickerTitleTime": "Select time",
	    "dxDateBox-validation - datetime": "Value must be a date or time",
	    "dxFileUploader-Gb": "Gb",
	    "dxFileUploader-Mb": "Mb",
	    "dxFileUploader-bytes": "bytes",
	    "dxFileUploader-dropFile": "or Drop file here",
	    "dxFileUploader-kb": "kb",
	    "dxFileUploader-readyToUpload": "Ready to upload",
	    "dxFileUploader-selectFile": "Select file",
	    "dxFileUploader-upload": "Upload",
	    "dxFileUploader-uploadFailedMessage": "Upload failed",
	    "dxFileUploader-uploaded": "Uploaded",
	    "dxForm-optionalMark": "optional",
	    "dxForm-requiredMessage": "{0} is required",
	    "dxList-nextButtonText": "More",
	    "dxList-pageLoadingText": "Loading...",
	    "dxList-pulledDownText": "Release to refresh...",
	    "dxList-pullingDownText": "Pull down to refresh...",
	    "dxList-refreshingText": "Refreshing...",
	    "dxList-selectAll": "전체",
	    "dxListEditDecorator - delete": "Delete",
	    "dxListEditDecorator - more": "More",
	    "dxLookup - searchPlaceholder": "Minimum character number {0}",
	    "dxNumberBox - invalidValueMessage": "Value must be a number",
//	    "dxPager-infoText": "{0}/{1}페이지 (전체 {2}건)",
	    "dxPager-infoText": "전체 {2}건",
	    "dxPager-pagesCountText": "of",
	    "dxPivotGrid-allFields": "전체 필드",
	    "dxPivotGrid-collapseAll": "전체접기",
	    "dxPivotGrid-columnFieldArea": "조회할 컬럼필드를 여기에 드래그 하세요",
	    "dxPivotGrid-columnFields": "컬럼필드",
	    "dxPivotGrid-dataFieldArea": "조회할 데이터필드를 여기에 드래그 하세요",
	    "dxPivotGrid-dataFields": "데이터필드",
	    "dxPivotGrid-expandAll": "전체펼치기",
	    "dxPivotGrid-fieldChooserTitle": "필드선택기",
	    "dxPivotGrid-filterFieldArea": "조회할 필터필드를 여기에 드래그 하세요",
	    "dxPivotGrid-filterFields": "필터필드",
	    /* DOGFOOT ktkang KERIS 전체 합계 문구 변경  20200116 */
	    "dxPivotGrid-grandTotal": "총계",
	    "dxPivotGrid-removeAllSorting": "전체 정렬제거",
//	    "dxPivotGrid-rowFieldArea": "로우를 여기에 드래그 하세요",
		/* goyong ktkang 고용정보원 커스터마이징  20210514 */
	    "dxPivotGrid-rowFieldArea": " ",
	    "dxPivotGrid-rowFields": "로우필드",
	    "dxPivotGrid-showFieldChooser": "필터선택기 보기",
	    "dxPivotGrid-sortColumnBySummary": "Sort {0} by This Column",
	    "dxPivotGrid-sortRowBySummary": "Sort {0} by This Row ",
	    "dxPivotGrid-total": "{0} 전체",
	    "dxRangeSlider-ariaFrom": "From",
	    "dxRangeSlider-ariaTill": "Till",
	    "dxScheduler-allDay": "All day",
	    "dxScheduler-confirmRecurrenceDeleteMessage": "Do you want to delete only this appointment or the whole series?",
	    "dxScheduler-confirmRecurrenceDeleteOccurrence": "Delete appointment",
	    "dxScheduler-confirmRecurrenceDeleteSeries": "Delete series",
	    "dxScheduler-confirmRecurrenceEditMessage": "Do you want to edit only this appointment or the whole series?",
	    "dxScheduler-confirmRecurrenceEditOccurrence": "Edit appointment",
	    "dxScheduler-confirmRecurrenceEditSeries": "Edit series",
	    "dxScheduler-editorLabelDescription": "Description",
	    "dxScheduler-editorLabelEndDate": "End Date",
	    "dxScheduler-editorLabelRecurrence": "Repeat",
	    "dxScheduler-editorLabelStartDate": "Start Date",
	    "dxScheduler-editorLabelTitle": "Subject",
	    "dxScheduler-noTimezoneTitle": "No timezone",
	    "dxScheduler-openAppointment": "Open appointment",
	    "dxScheduler-recurrenceAfter": "After",
	    "dxScheduler-recurrenceDaily": "Daily",
	    "dxScheduler-recurrenceEnd": "End repeat",
	    "dxScheduler-recurrenceEvery": "Every",
	    "dxScheduler-recurrenceMonthly": "Monthly",
	    "dxScheduler-recurrenceNever": "Never",
	    "dxScheduler-recurrenceOn": "On",
	    "dxScheduler-recurrenceRepeatCount": "occurrence(s)",
	    "dxScheduler-recurrenceRepeatDaily": "day(s)",
	    "dxScheduler-recurrenceRepeatMonthly": "month(s)",
	    "dxScheduler-recurrenceRepeatOnDate": "on date",
	    "dxScheduler-recurrenceRepeatWeekly": "week(s)",
	    "dxScheduler-recurrenceRepeatYearly": "year(s)",
	    "dxScheduler-recurrenceWeekly": "Weekly",
	    "dxScheduler-recurrenceYearly": "Yearly",
	    "dxScheduler-switcherAgenda": "Agenda",
	    "dxScheduler-switcherDay": "Day",
	    "dxScheduler-switcherMonth": "Month",
	    "dxScheduler-switcherTimelineDay": "Timeline Day",
	    "dxScheduler-switcherTimelineMonth": "Timeline Month",
	    "dxScheduler-switcherTimelineWeek": "Timeline Week",
	    "dxScheduler-switcherTimelineWorkWeek": "Timeline Work Week",
	    "dxScheduler-switcherWeek": "Week",
	    "dxScheduler-switcherWorkWeek": "Work week",
	    "dxScrollView-pulledDownText": "Release to refresh...",
	    "dxScrollView-pullingDownText": "Pull down to refresh...",
	    "dxScrollView-reachBottomText": "Loading...",
	    "dxScrollView-refreshingText": "Refreshing...",
	    "dxSwitch-offText": "OFF",
	    "dxSwitch-onText": "ON",
	    "validation-compare": "Values do not match",
	    "validation-compare-formatted": "{0} does not match",
	    "validation-custom": "Value is invalid",
	    "validation-custom-formatted": "{0} is invalid",
	    "validation-email": "Email is invalid",
	    "validation-email-formatted": "{0} is invalid",
	    "validation-mask": "Value is invalid",
	    "validation-numeric": "Value must be a number",
	    "validation-numeric-formatted": "{0} must be a number",
	    "validation-pattern": "Value does not match pattern",
	    "validation-pattern-formatted": "{0} does not match pattern",
	    "validation-range": "Value is out of range",
	    "validation-range-formatted": "{0} is out of range",
	    "validation-required": "Required",
	    "validation-required-formatted": "{0} is required",
	    "validation-stringLength": "The length of the value is not correct",
	    "validation-stringLength-formatted": "The length of {0} is not correct",
	    "vizExport-exportButtonText": "{0} file",
	    "vizExport-printingButtonText": "Print",
	    "vizExport-titleMenuText": "Exporting/Printing"
	}
});

