package com.wise.ds.repository.service;

import java.util.HashMap;
import java.util.List;

import com.wise.ds.repository.AnalysisLogVO;
import com.wise.authn.ConfigMasterVO;
import com.wise.authn.DataSourceGRPVO;
import com.wise.authn.DataSourceUserVO;
import com.wise.authn.DataSourceVO;
import com.wise.authn.User;
import com.wise.authn.UserSessionVO;
import com.wise.authn.WebConfigMasterVO;
import com.wise.ds.repository.CubeVO;
import com.wise.ds.repository.CurrentSqlVO;
import com.wise.ds.repository.DSViewDimVO;
import com.wise.ds.repository.DSViewHieVO;
import com.wise.ds.repository.DSViewVO;
import com.wise.ds.repository.DashLoginOutMasterVO;
import com.wise.ds.repository.DashReportMasterVO;
import com.wise.ds.repository.ExportLogVO;
import com.wise.ds.repository.FolderMasterVO;
import com.wise.ds.repository.GrpAuthDataSetVO;
import com.wise.ds.repository.UserGrpAuthReportListVO;
import com.wise.ds.repository.AuthReportVO;
import com.wise.ds.repository.GrpListVO;
import com.wise.ds.repository.InsertGroupAuthDataSetVO;
import com.wise.ds.repository.InsertUserAuthDataSetVO;
import com.wise.ds.repository.JobListVO;
import com.wise.ds.repository.LogParamVO;
import com.wise.ds.repository.QueryLogVO;
import com.wise.ds.repository.ReportListMasterVO;
import com.wise.ds.repository.ReportMasterVO;
import com.wise.ds.repository.SameTimeConVO;
import com.wise.ds.repository.SessionParamVO;
import com.wise.ds.repository.UserAuthDataSetVO;
import com.wise.ds.repository.UserConfigVO;
import com.wise.ds.repository.PublicFolderListVO;
import com.wise.authn.UserGroupVO;

public interface ConfigService {
	public List<JobListVO> selectJobListMaster();
	public List<SameTimeConVO> selectSameTimeConMaster();
	public List<UserGroupVO> selectUserListAndGroupName();
	public int selectUserCnt();
	public List<DataSourceVO> selectDataSourceList(List<Integer> id);
	public List<DataSourceUserVO> selectDataSourceUserList(int no);
	public List<DataSourceGRPVO> selectDataSourceGRPList(int no);
	public Integer selectGroupIdByGroupName(String groupName);
	public void updateUserList(UserGroupVO userInfo);
	public void updateDatasourceList(DataSourceVO datasource);
	public void insertNewUser(UserGroupVO userInfo);
	//2020.12.21 syjin 환경 설정 원본 추가 insert 설정
	public int insertNewDatasource(DataSourceVO datasource);
	public int insertNewDatasourceUser(DataSourceUserVO datasourceUser);
	public List<UserGroupVO> selectGroupList();
	public void deleteUserFromList(UserGroupVO userInfo);
	public int deleteDataSourceInfo(DataSourceVO datasource);
	public int deleteDataSourceUserInfo(DataSourceUserVO datasourceUser);
	public void changeUserPassword(UserGroupVO userInfo);
	public void insertGroupInfo(UserGroupVO groupInfo);
	public void updateGroupInfo(UserGroupVO groupInfo);
	public void deleteGroupInfo(UserGroupVO groupInfo);
	public List<UserGroupVO> selectUserList();
	public List<DSViewVO> selectDSViewList();
	public List<UserAuthDataSetVO> selectUserAuthDataSet(int userNo);
	public List<CubeVO> selectCubeList(int dsViewId);
	public List<DSViewDimVO> selectDSViewDimList(int dsViewId);
	public List<DSViewHieVO> selectDSViewHieList(int dsViewId);
	public void initUserDataAuth(int userNo);
	public void insertUserAuthData(InsertUserAuthDataSetVO authVo);
	public List<UserGrpAuthReportListVO> selectGrpAuthFolderList(String grpId);
	public List<UserGrpAuthReportListVO> selectGrpAuthReportList(String grpId);
	public void initGrpFldAuth(int grpId);
	public int insertGrpFldAuth(AuthReportVO insertVo);
	public void initGrpReportAuth(int grpId);
	public int insertGrpReportAuth(AuthReportVO insertVo);
	public List<GrpListVO> selectGrpList();
	public List<PublicFolderListVO> selectPubFolderList();
	public List<PublicFolderListVO> selectPubFolderReportList();
	public void updateConfigMstr(ConfigMasterVO configVo);
	public List<CurrentSqlVO> selectCurrentSqlList(String ds_id);
	public int stopProcess(String session_id, String ds_id);
	public List<DashLoginOutMasterVO> selectDashLoginOutMaster(LogParamVO paramVo);
	public List<DashReportMasterVO> selectDashReportUseMaster(LogParamVO paramVo);
	public List<ExportLogVO> selectExportLog(LogParamVO paramVo);
	public List<AnalysisLogVO> selectAnalysisLog();
	public List<QueryLogVO> selectQueryLog(LogParamVO paramVo);
	public List<ReportListMasterVO> selectPublicReportList();
	public void deletePublicReport(Integer id);
	public void savePublicReport(ReportListMasterVO report);
	public void addUserToGroup(UserGroupVO user);
	public void removeUserFromGroup(UserGroupVO user);
	public List<FolderMasterVO> getPublicFolderList();
	public int getPublicFolderLevel(Integer parentFldId);
	public int getPublicFolderMaxOrdinal(Integer parentFldId);
	public void insertPublicFolder(FolderMasterVO folder);
	public FolderMasterVO getPublicFolderWithNameAndParent(FolderMasterVO folder);
	public void editPublicFolderName(FolderMasterVO folder);
	public List<ReportMasterVO> selectReportsInFolders(List<Integer> folders);
	public void deleteChildFolders(List<Integer> folders);
	public void deleteChildReports(List<Integer> folders);
	public void deleteFolder(Integer folderId);
	public List<UserSessionVO> selectUserSessions(SessionParamVO paramVo);
	/* DOGFOOT ktkang 동시 접속자 현황에서 하루 지난 로그인 아이디 삭제  20200922 */
	public void deleteUserSessionsByDate(SessionParamVO paramVo);
	public List<UserSessionVO> selectInactiveUserSessions(SessionParamVO paramVo);
	public List<UserGroupVO> selectLockedUserSessions();
	public List<FolderMasterVO> selectDatasetFolderList();
	public List<FolderMasterVO> selectGrpDatasetAuth(String grpId);
	public void initGrpDatasetAuth(Integer grpId);
	public void insertGrpDatasetAuth(GrpAuthDataSetVO grpAuthVo);
	public List<GrpAuthDataSetVO> selectGroupAuthDataSet(int groupNo);
	public void initGroupDataAuth(int groupId);
	public void insertGroupAuthData(InsertGroupAuthDataSetVO authVo);
	public List<UserGrpAuthReportListVO> selectUserAuthFolderList(Integer userNo);
	public List<UserGrpAuthReportListVO> selectUserAuthReportList(Integer userNo);
	public void initUserFldAuth(int userNo);
	public void insertUserFldAuth(AuthReportVO insertVo);
	public void initUserReportAuth(int userNo);
	public void insertUserReportAuth(AuthReportVO insertVo);
	public List<FolderMasterVO> selectUserDatasetAuth(Integer userNo);
	public void initUserDatasetAuth(Integer userNo);
	public void insertUserDatasetAuth(UserAuthDataSetVO userAuthVo);
	public void updateWebConfigMstr(WebConfigMasterVO webConfigVo);
	public void initGroupUsers(Integer groupId);
	public void updateGroupUsers(UserGroupVO userGroupVo);
	public List<UserGroupVO> selectUserAuthDataList();
	public List<UserGroupVO> selectGroupAuthDataList();
	public List<UserGroupVO> selectGroupAuthDsList();
	public List<UserGroupVO> selectUserAuthDsList();
	public List<DataSourceVO> selectDsList();
	public List<DataSourceGRPVO> selectGrpDsAuth(String grpId);
	public List<DataSourceUserVO> selectUserDsAuth(Integer userNo);
	public List<UserGroupVO> selectUserDatasetList();
	public List<UserGroupVO> selectGroupDatasetList();
	public UserConfigVO selectUserConfig(Integer userNo);
	public void insertUserConfig(UserConfigVO userConfig);
	public void updateUserProfile(User user, UserConfigVO userConfig);
	public void updateUserDatasetId(UserConfigVO userConfig);
	public void updateUserReportInfo(UserConfigVO userConfig);
	public void updateUserItem(UserConfigVO userConfig);
	public void updateUserPalette(UserConfigVO userConfig);
	public void updateUserViewerReportInfo(UserConfigVO userConfig);
	public void updateUserFontConfig(UserConfigVO userConfig);
	/* DOGFOOT ktkang 개인보고서 추가  20200107 */
	public List<ReportListMasterVO> selectUserReportList(int user_id);
	public List<FolderMasterVO> getUserFolderList(int user_no);
	public void deleteChildUserFolders(List<Integer> folders);
	public void deleteUserFolder(int folderId);
	public FolderMasterVO getUserFolderWithNameAndParent(FolderMasterVO folder);
	public void editUserFolderName(FolderMasterVO folder);
	public int getUserFolderLevel(Integer parentFldId);
	public int getUserFolderMaxOrdinal(Integer parentFldId);
	public void insertUserFolder(FolderMasterVO folder);
	public int deleteDataSourceGrpInfo(DataSourceGRPVO datasourceGrp);
	void initGrpDsAuth(Integer grpId);
	void initUserDsAuth(Integer userNo);
	void insertUserDsAuth(DataSourceUserVO userAuthVo);
	void insertGrpDsAuth(DataSourceGRPVO grpAuthVo);
	public List<HashMap> selectGrpWbAuth(String grpId);
	public List<HashMap> selectUserWbAuth(Integer userNo);
	public List<UserGroupVO> selectUserWbList();
	public List<UserGroupVO> selectGroupWbList();
	void initUserWbAuth(Integer userNo);
	void insertUserWbAuth(HashMap userAuth);
	void initGrpWbAuth(Integer grpId);
	void insertGrpWbAuth(HashMap grpAuth);
}