/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.wise.comp.pivotmatrix.schema.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AvroSummaryCell extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4613833249986069590L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AvroSummaryCell\",\"namespace\":\"com.wise.comp.pivotmatrix.schema.avro\",\"fields\":[{\"name\":\"summaryValues\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"AvroSummaryValue\",\"fields\":[{\"name\":\"fieldName\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"summaryType\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"count\",\"type\":\"long\"},{\"name\":\"sum\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"value\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]},{\"name\":\"distinctValues\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}},{\"name\":\"textValue\",\"type\":[{\"type\":\"string\",\"avro.java.string\":\"String\"},\"null\"]}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AvroSummaryCell> ENCODER =
      new BinaryMessageEncoder<AvroSummaryCell>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AvroSummaryCell> DECODER =
      new BinaryMessageDecoder<AvroSummaryCell>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<AvroSummaryCell> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<AvroSummaryCell> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AvroSummaryCell>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this AvroSummaryCell to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a AvroSummaryCell from a ByteBuffer. */
  public static AvroSummaryCell fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryValue> summaryValues;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AvroSummaryCell() {}

  /**
   * All-args constructor.
   * @param summaryValues The new value for summaryValues
   */
  public AvroSummaryCell(java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryValue> summaryValues) {
    this.summaryValues = summaryValues;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return summaryValues;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: summaryValues = (java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryValue>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'summaryValues' field.
   * @return The value of the 'summaryValues' field.
   */
  public java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryValue> getSummaryValues() {
    return summaryValues;
  }

  /**
   * Sets the value of the 'summaryValues' field.
   * @param value the value to set.
   */
  public void setSummaryValues(java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryValue> value) {
    this.summaryValues = value;
  }

  /**
   * Creates a new AvroSummaryCell RecordBuilder.
   * @return A new AvroSummaryCell RecordBuilder
   */
  public static com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell.Builder newBuilder() {
    return new com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell.Builder();
  }

  /**
   * Creates a new AvroSummaryCell RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AvroSummaryCell RecordBuilder
   */
  public static com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell.Builder newBuilder(com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell.Builder other) {
    return new com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell.Builder(other);
  }

  /**
   * Creates a new AvroSummaryCell RecordBuilder by copying an existing AvroSummaryCell instance.
   * @param other The existing instance to copy.
   * @return A new AvroSummaryCell RecordBuilder
   */
  public static com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell.Builder newBuilder(com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell other) {
    return new com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell.Builder(other);
  }

  /**
   * RecordBuilder for AvroSummaryCell instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AvroSummaryCell>
    implements org.apache.avro.data.RecordBuilder<AvroSummaryCell> {

    private java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryValue> summaryValues;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.summaryValues)) {
        this.summaryValues = data().deepCopy(fields()[0].schema(), other.summaryValues);
        fieldSetFlags()[0] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AvroSummaryCell instance
     * @param other The existing instance to copy.
     */
    private Builder(com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.summaryValues)) {
        this.summaryValues = data().deepCopy(fields()[0].schema(), other.summaryValues);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'summaryValues' field.
      * @return The value.
      */
    public java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryValue> getSummaryValues() {
      return summaryValues;
    }

    /**
      * Sets the value of the 'summaryValues' field.
      * @param value The value of 'summaryValues'.
      * @return This builder.
      */
    public com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell.Builder setSummaryValues(java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryValue> value) {
      validate(fields()[0], value);
      this.summaryValues = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'summaryValues' field has been set.
      * @return True if the 'summaryValues' field has been set, false otherwise.
      */
    public boolean hasSummaryValues() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'summaryValues' field.
      * @return This builder.
      */
    public com.wise.comp.pivotmatrix.schema.avro.AvroSummaryCell.Builder clearSummaryValues() {
      summaryValues = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AvroSummaryCell build() {
      try {
        AvroSummaryCell record = new AvroSummaryCell();
        record.summaryValues = fieldSetFlags()[0] ? this.summaryValues : (java.util.List<com.wise.comp.pivotmatrix.schema.avro.AvroSummaryValue>) defaultValue(fields()[0]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AvroSummaryCell>
    WRITER$ = (org.apache.avro.io.DatumWriter<AvroSummaryCell>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AvroSummaryCell>
    READER$ = (org.apache.avro.io.DatumReader<AvroSummaryCell>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
